# Job name has to be `pages`. See https://docs.gitlab.com/ee/user/project/pages/#how-it-works
image: node:22

pages:
    stage: build
    cache:
        - key:
              files:
                  - yarn.lock
          paths:
              - .yarn-cache/
    before_script:
        - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
        - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
        - yarn install --frozen-lockfile
    script:
        - export NUXT_APP_BASE_URL="/${CI_PROJECT_NAME}/"
        - export NUXT_STUDIO="false"
        - yarn generate
        - rm -rf public
        - mkdir -p public
        - cp -a .output/public/. public/
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: never
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
