# Job name has to be `pages`. See https://docs.gitlab.com/ee/user/project/pages/#how-it-works
image: node:22-bookworm-slim

pages:
    stage: build
    variables:
        NUXT_APP_BASE_URL: "/greatbay-scie/"
        NODE_OPTIONS: "--max-old-space-size=8192"
    cache:
        - key:
              files:
                  - yarn.lock
                  - package.json
          paths:
              - .yarn/cache/

        - key:
              prefix: build-cache-$CI_COMMIT_REF_SLUG
              files:
                  - yarn.lock
          paths:
              - node_modules/.cache/
    before_script:
        - corepack enable
        - yarn install --immutable --inline-builds
    script:
        - yarn generate
        - mkdir -p public
        - cp -a .output/public/. public/
    artifacts:
        paths:
            - public
