name: Push to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

permissions:
  contents: read

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push branch or tag to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPOSITORY: gitlab.igem.org/2026/greatbay-scie.git
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPOSITORY}"

          if [ "${GITHUB_REF_TYPE}" = "branch" ]; then
            git push gitlab "HEAD:${GITHUB_REF_NAME}"
          elif [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            git push gitlab "refs/tags/${GITHUB_REF_NAME}:refs/tags/${GITHUB_REF_NAME}"
          fi
